version: '3'
services:
  rotondo-server:
    restart: always
    build: .
    ports: 
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo-db:27017

    networks:
      - rotondo-network
  mongo-db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - rotondo-network

volumes:
  mongodb:

networks:
  rotondo-network: